name: publish
run-name: Publish ${{ github.ref_name }} to Modrinth and CurseForge

on:
    workflow_dispatch:

    release:
        types:
            - published

jobs:
    publish:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - name: Download release assets
              run: gh release download ${{ github.ref_name }} --repo ${{ github.repository }} --pattern '*.jar' --dir 'build/libs/'
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Publish release assets to Modrinth and CurseForge
              uses: Kir-Antipov/mc-publish@v3.3
              with:
                  java: 17

                  modrinth-id: uFJODQCA
                  modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
                  modrinth-featured: false

                  curseforge-id: 645296
                  curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
