name: release
run-name: Release artifacts

on: workflow_dispatch

env:
  ENVIRONMENT: "production"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Upload release artifacts
        run: ./gradlew build modrinth github --stacktrace

      - name: Capture artifacts
        with:
            name: Artifacts
            path: build/libs/
